Add SetExcludeScheme method.
zenhack/go.notmuch pull request #18
Opened 2019-07-14 13:06 UTC by brunnre8

Maps to notmuch_query_set_omit_excluded and allows to change the
exclude behaviour of a query.

Please carefully look over the C calling stuff... I don't normally write C go and may have missed something

2019-07-14 18:32 UTC, zenhack commented
Looks like the failures are because I haven't updated the build matrix in a while, so it's still testing on super old versions of Go.

At a glance this looks reasonable, I'll have a closer look soonish.

Thanks for the patch!

2019-07-15 23:20 UTC, zenhack requested changes
A few minor comments.

I'll fuss with the CI bitrot myself soonish; in the meantime I'll just test locally.

2019-07-15 23:20 UTC, zenhack commented on query.go
> +	QUERY_EXCLUDE_FLAG = C.NOTMUCH_EXCLUDE_FLAG
Let's omit the `QUERY_*` prefix, and just call it `EXCLUDE_FLAG` (and likewise with the other constants).

2019-07-15 23:20 UTC, zenhack commented on query.go
> +	// notmuch_query_search_messages and notmuch_query_search_threads
Use the names for the go wrappers, rather than the c identifiers -- so in this case Query.SearchMessages.

2019-07-16 00:52 UTC, zenhack commented
I switched us over to gitlab ci on master; you'll need to fix the merge conflicts (shouldn't be hard).

2019-07-16 05:14 UTC, brunnre8 commented
Note that Query.SearchMessages isn't actually implemented yet.... :wink: 

I thought it was, but only Query.Threads actually is...

I'll try and patch that up in a separate PR if you don't beat me to it.
Which would you prefer? Query.SearchMessages or Query.Messages?

I think we should stay consistent with the way threads are queried

2019-07-16 06:41 UTC, merged