Add support for notmuch properties
zenhack/go.notmuch pull request #29
Opened 2021-10-20 00:10 UTC by stbenjam

From https://git.notmuchmail.org/git/notmuch/blob/HEAD:/lib/notmuch.h:

```
This interface provides the ability to attach arbitrary (key,value)
string pairs to a message, to remove such pairs, and to iterate
over them.  The caller should take some care as to what keys they
add or delete values for, as other subsystems or extensions may
depend on these properties.

Please see notmuch-properties(7) for more details about specific
properties and conventions around their use.
```

2021-10-21 20:08 UTC, zenhack requested changes
Thanks for the patch! A couple minor issues pointed out in-line.

2021-10-21 20:08 UTC, zenhack commented on message.go
> +	cprops := C.notmuch_message_get_properties(m.toC(), C.CString(key), C.int(cexact))
There's a memory leak here (the key)

2021-10-21 20:08 UTC, zenhack commented on properties.go
> +type Properties cStruct
Perhaps we should call this `MessageProperties`? I could conceive of the C library adding e.g. `notmuch_thread_properties_t` later on.

2021-10-22 02:03 UTC, stbenjam commented
@zenhack Please have another look.  I also added some test coverage

2021-10-22 19:14 UTC, zenhack approved these changes
LGTM, thanks.

2021-10-22 19:14 UTC, merged